### ISSUE TITLE
Incompatible GPL license on pngquant-bin 

### ISSUE THREAD

**Issue by rjmackay** [tcoopman/image-webpack-loader#322]
pngquant-bin (used by imagemin-pngquant) is licensed under GPLv3 which is incompatible with this packages MIT license.

**Comment by tcoopman** [comment]
[pngquant-bin](https://github.com/imagemin/pngquant-bin) links on their readme to [imgaemin-pngquant](https://github.com/imagemin/imagemin-pngquant) which is also MIT (I see that you also created an issue over there - https://github.com/imagemin/imagemin-pngquant/issues/77)

![image](https://user-images.githubusercontent.com/45546/114004891-5c225100-985f-11eb-9ed7-68b654ec256b.png)

So that seems like they allow it to be used with the MIT license.

**Comment by tcoopman** [comment]
Doing some further investigation, I see that pngquant-bin changed their license and they concluded that imagemin-pngquant can use it because they wrap it (https://github.com/imagemin/pngquant-bin/pull/105).

**Comment by rjmackay** [comment]
Thanks for the quick response!

> they concluded that imagemin-pngquant can use it because they wrap it

Maybe I misread? I thought they changed their license because they concluded it COULDN'T be used under MIT terms so had to be GPL.

The issue probably needs to be resolved within imagemin-pngquant first anyway. However there's a risk that including the GPL'd code within image-webpack-loader means it should be released as GPL. It's not something I can risk in my codebases so I've disabled image-webpack-loader for now.

Any thoughts on if it'd be possible to make https://github.com/imagemin/imagemin-pngquant an optional dependency and only load it when it's used?
