### ISSUE TITLE
pngquant: Command Failed

### ISSUE THREAD

**Issue by EliasJorgensen** [tcoopman/image-webpack-loader#45]
Hi, i'm trying to compress a PNG with the example settings you provided in the README file:
```
'image-webpack?{progressive:true, optimizationLevel: 7, interlaced: false, pngquant:{quality: "65-90", speed: 4}}'
```
However, when i run my build, i get this error:
```
ERROR in ./src/assets/images/highResHell.png
Module build failed: Error: Command failed: /home/elias/Projects/Javascript/idexdanmark/node_modules/pngquant-bin/vendor/pngquant --output /tmp/012c00ce-0e87-4c68-bfa8-185586e92037 /tmp/7add16f3-8bf9-4ad2-b370-ad97ce2b9856 --quality 65-90 --speed 4

    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:852:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
 @ ./src/components/ExampleComponent/index.js 7:19-59

```

I tried removing my node_modules folder and reinstalling my dependencies, but it had no effect.

**Comment by ldbglobe** [comment]
Same issue reported here without a real fix (but with an alternative solution)
https://github.com/tcoopman/image-webpack-loader/issues/42

**Comment by EliasJorgensen** [comment]
I also switched to img-loader in my search for a fix. I guess the issue is closed :P

**Comment by lox** [comment]
Except img-loader still has the same error, it just doesn't cause the entire process to fail.

**Comment by tcoopman** [comment]
Can you please report this with pngquant? Looks like a bug there.

**Comment by zeh** [comment]
Also having an issue with this. I keep dropping my quality to get it to run, but then I add a new png and it stops working again.

Even though pngquant seems to be the one taking too long to run (how is that determined?) it doesn't change the fact that the whole webpack deployed is broken because of that.

**Comment by Saborknight** [comment]
Hey! @zeh thanks for this, but how would I implement this with laravel-mix webpack? I'm unsure about how to proceed with it. Thanks!

**Comment by zeh** [comment]
@Saborknight not sure, I don't use laravel-mix. But, somewhere on your node_modules dependencies there must be a `image-webpack-loader` folder. Inside of it there's a `index.js` file, to which you can apply the above change.

Again, not recommended, since this changes your installed modules and it can be overwritten if you reinstall (and no one else using the same repo will have the same version). But works in a pinch.

I hadn't had the time to open a PR on imagemin yet, sorry. That would be the right way to fix this. Of course image-webpack-loader could also fix this, but it's a deeper problem.

**Comment by Saborknight** [comment]
@zeh Thanks for the pointers. I don't understand why this issue is closed when it is definitely not a resolved issue!

**Comment by tcoopman** [comment]
@zeh if you create a PR for your change, I can add that. Fixing imagemin would be better of course :)

**Comment by zeh** [comment]
Huh. I was looking into opening the PR for imagemin (actually [imagemin-pngquant](https://github.com/imagemin/imagemin-pngquant)) but apparently [it was just fixed](https://github.com/imagemin/imagemin-pngquant/pull/33) in Jan 25 2017.

The bad news is that imagemin-pngquant had no official release since that commit; latest was 5.0.0 in on Apr 29, 2016. But as soon as that is released, it's just a matter of image-webpack-loader updating the dependency.

**Comment by alopes** [comment]
```npm install imagemin/imagemin-pngquant --save``` did it for me.

**Comment by Radicaly2k** [comment]
Great solution @alopes

**Comment by liverpoolrc** [comment]
Solution - 

- cd THEME
- npm install imagemin/imagemin-pngquant --save

**Comment by nicooprat** [comment]
Upgrading to `imagemin-pngquant@^5.0.1` worked for me, even with default quality options (>50).

**Comment by nicooprat** [comment]
Optimizing large PNGs (1Mo) is very complicated: `pngquant` was crashing, and `optipng` is very slow with almost no difference in resulting image (quality or weight). Using roots/sage, optimizing a few PNGs took more than 200 seconds! Is it normal? What's the point of using two different librairies for optimizing PNGs?
