### ISSUE TITLE
bypassOnDebug seems not to be working

### ISSUE THREAD

**Issue by Gautierrr** [tcoopman/image-webpack-loader#70]
I've made many tests using **Webpack 2** and **image-webpack-loader 3.1.0**
bypassOnDebug seems not to be working (either in global options or in mozjpeg options)

```js
{
 loader  : "image-webpack-loader",
 options : {
    bypassOnDebug : true,
    mozjpeg       : { bypassOnDebug: true, quality: 5, progressive: true },
    optipng       : { optimizationLevel: 7 },
    gifsicle      : { interlaced: false }
  }
}
```

Also, the README associates `bypassOnDebug` exclusively with `mozjpeg` but `bypassOnDebug` is global to the loader right? ([mozjpeg](https://github.com/imagemin/imagemin-mozjpeg) doesn't show any `bypassOnDebug` option)

**Comment by TomDeBacker** [comment]
If bypassOnDebug is set to true none of the image optimizers will be executed. It's not only associated with mozjpeg.

The plugin checks for this.debug **AND** bypassOnDebug to be true. 
`if (this.debug === true && options.bypassOnDebug === true)`

So might need to set this.debug aswell. Pay notice that how you set `debug` changed since webpack 2.

**Comment by yvele** [comment]
@TomDeBacker Sorry we misconfigured Webpack.. we did

```js
new webpack.LoaderOptionsPlugin({
      options   : {
         minimize  : config.minimize,
         debug     : config.debug
     }
}
```

instead of

```js
new webpack.LoaderOptionsPlugin({
      minimize  : config.minimize,
      debug     : config.debug
      options   : {
         minimize  : !config.debug,
         debug     : config.debug
     }
}
```

we can close this issue

**Comment by TomDeBacker** [comment]
:+1:

**Comment by yvele** [comment]
@Gautierrr Can you close?
